# This is a basic workflow to help you get started with Actions

name: linux-x64-gpu

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  ci_debug_linux-x64:
    runs-on: [self-hosted, gpu]

    steps:
      - name: clear
        run: sudo rm -rf ./*

      - uses: actions/checkout@v3

      - name: build
        run: |
          docker run --runtime=nvidia --rm -v $(pwd):/workspace \
            --name build-ort-gpu-linx-x64 seungtaek/cuda:11.6.2-cudnn8-devel-ubuntu20.04 ./build.sh
      
        



