# This is a basic workflow to help you get started with Actions

name: windows-x64-cpu

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build_windows-x64-cpu:
    runs-on: windows-2019

    steps:
      - uses: actions/checkout@v3

      - name: Setup cmake
        uses: jwlawson/actions-setup-cmake@v1.12
        with:
          cmake-version: '3.23.x'

      - name: Build
        run: .\build.bat

      - name: Test
        run: |
          cd .\win-x64\Debug
          .\test_orthandler.exe