# This is a basic workflow to help you get started with Actions

name: Linux-x64

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  ci_debug_linux-x64:
    runs-on: [self-hosted, gpu]

    steps:
      - uses: actions/checkout@v3

      - name: Setup cmake
        uses: jwlawson/actions-setup-cmake@v1.12
        with:
          cmake-version: '3.23.x'

      - name: Build Onnxruntime Handler
        run: ./build.sh

      - name: Run gTest
        run: |
          cd ./linux-x64/Debug
          ./test_orthandler

      - name: gpu
        run: |
          docker run --rm --gpus all nvidia/cuda:11.0-base nvidia-smi
        



